app_root: .
ignored_folders:
- vendor
- log
- logs
- grifts
- tmp
- bin
included_extensions:
- .go
- .env
build_path: tmp
build_delay: 200ns
binary_name: conduit-build
command_flags: []
enable_colors: true
log_name: buffalo
